name: task-management-app
on: [push]
jobs:
  task-management-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkoutv2
      
      - run: cd src
      - run: yarn install
      - run: yarn test 